language: perl6

os:
  - linux

perl6:
  - latest

install:
  - rakudobrew build zef
  - zef -v install --deps-only .
  - zef install TAP::Harness
  - PERL6LIB=lib perl6 -MTAP -e 'exit(TAP::Harness.new.run(@*ARGS).result.has-errors)' t/*.t6

