language: perl6

os:
  - linux

perl6:
  - latest

install:
  - rakudobrew build zef
  - zef -v install --deps-only .
  - zef install App::Prove6
  - /home/travis/.rakudobrew/moar-master/install/share/perl6/site/bin/prove6
